# Generated by Django 5.2.15 on 2026-07-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("hr", "HR"), ("applicant", "Applicant")],
                default="applicant",
                max_length=20,
            ),
        ),
    ]
