# Generated by Django 5.2.15 on 2026-07-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("employer", "Employer"), ("applicant", "Applicant")],
                default="applicant",
                max_length=20,
            ),
        ),
    ]
