APPLICATION_STATUS_PENDING = "pending"
APPLICATION_STATUS_REVIEWING = "reviewing"
APPLICATION_STATUS_ACCEPTED = "accepted"
APPLICATION_STATUS_REJECTED = "rejected"

APPLICATION_STATUS_CHOICES = (
    (APPLICATION_STATUS_PENDING, "Pending"),
    (APPLICATION_STATUS_REVIEWING, "Reviewing"),
    (APPLICATION_STATUS_ACCEPTED, "Accepted"),
    (APPLICATION_STATUS_REJECTED, "Rejected"),
)

# قوانین تغییر وضعیت (مهم‌ترین بخش)
ALLOWED_TRANSITIONS = {
    APPLICATION_STATUS_PENDING: [
        APPLICATION_STATUS_REVIEWING,
        APPLICATION_STATUS_REJECTED,
    ],
    APPLICATION_STATUS_REVIEWING: [
        APPLICATION_STATUS_ACCEPTED,
        APPLICATION_STATUS_REJECTED,
    ],
    APPLICATION_STATUS_ACCEPTED: [],
    APPLICATION_STATUS_REJECTED: [],
}


def can_change_status(current, new):
    return new in ALLOWED_TRANSITIONS.get(current, [])